CREATE TABLE IF NOT EXISTS plat_model(
    id VARCHAR(50) PRIMARY KEY NOT NULL,
    plat_nomor VARCHAR(255) NOT NULL,
    is_exit BOOLEAN DEFAULT FALSE,
    entered TIMESTAMPTZ DEFAULT NOW(), 
    exited TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
)